### ISSUE TITLE
You can log in

### ISSUE THREAD

**Issue by IanAragonSaenz** [IanAragonSaenz/Stuff-Trading-App#4]
Let users with existing accounts log in.

- [x] Set up login view controller.
  - [x] Button for log in
  - [x] Username and password text field.
- [x] Set connection with parse.
- [x] Make segue from login to tab bar.

**Comment by IanAragonSaenz** [comment]
#Tasks

- [ ] Set up login view controller.
  - [ ] Button for log in
  - [ ] Username and password text field.
- [ ] Set connection with parse.
- [ ] Make segue from login to tab bar.
